### ISSUE TITLE
I am unable to deploy global parameters.

### ISSUE THREAD

**Issue by bretvert** [Azure-Player/azure.datafactory.tools#396] opened 2024-06-12 15:10 UTC
**Describe the bug**
I am unable to deploy global parameters.

i dont using incremental deployment and When I activate incremental deployment, I receive the following error message:

##[error]The remote server returned an error: (404) Not Found.

**Expected behaviour**
![image](https://github.com/Azure-Player/azure.datafactory.tools/assets/10417440/de90ee67-9730-4a79-b203-c8a7a8830cbf)

**Screenshots**
![image](https://github.com/Azure-Player/azure.datafactory.tools/assets/10417440/1bd47fae-1739-4b3b-89b9-8d30ec792504)

![image](https://github.com/Azure-Player/azure.datafactory.tools/assets/10417440/ac650b5c-5c27-4479-a158-739c566c8227)

Help Please !!

**Comment by NowinskiK** [comment] 2024-06-12 16:37
Duplicate of #395

**Closed by NowinskiK** 2024-06-12 16:37 UTC
Labels: triage
