### ISSUE TITLE
No Space for SQL queries its getting added without space in datafactory under pipelines

### ISSUE THREAD

**Issue by zameer712** [Azure-Player/azure.datafactory.tools#275] opened 2023-01-13 10:43 UTC
**Describe the bug**
Spaces are not coming in between the queries and text which is being passed @NowinskiK  please help us here

When we are running the github actions its updating the query inside datafactory without space , please help in fixing it

![image](https://user-images.githubusercontent.com/102033066/212301037-462e06f2-0f1e-4d53-91a0-d9df86f536f2.png)

          Set-PSRepository -Name PSGallery -InstallationPolicy Trusted    
          Install-Module -Name Az.DataFactory -Repository PSGallery -Force          
          Install-Module -Name azure.datafactory.tools -Repository PSGallery -Force
          Import-Module -Name azure.datafactory.tools
          Update-Module -Name azure.datafactory.tools
          Get-Module -Name azure.datafactory.tools

**Comment by MarliesVeenes** [comment] 2023-01-13 17:38
This is a duplicate of #274, probably both issues have the same cause.

**Closed** 2023-01-13 20:23 UTC
Labels: duplicate
